### ISSUE TITLE
Rails 4 Support

### ISSUE THREAD

**Issue by aardvarkk** [krainboltgreene/jsonapi-realizer.rb#2]
This gem seems like it could be very helpful for a Rails 4 project I'm working on, but this gem has a dependency on ActiveSupport 5. Would it be much work to support Rails 4?

**Comment by krainboltgreene** [comment]
Very likely not! I'll investigate, unless you want to do this (or pair on this)?

**Comment by krainboltgreene** [comment]
Looks like the adapter is fine: https://github.com/krainboltgreene/jsonapi-realizer.rb/blob/core/lib/jsonapi/realizer/adapter/active_record.rb

**Comment by krainboltgreene** [comment]
I'm guessing the only hold back is: https://github.com/krainboltgreene/jsonapi-realizer.rb/blob/core/jsonapi-realizer.gemspec#L29

**Comment by aardvarkk** [comment]
OK, yeah -- I was assuming there was a reason behind the demand for ActiveSupport 5.1, but if not then maybe it can be lowered to 4.0 without losing any functionality?

**Comment by krainboltgreene** [comment]
@aardvarkk Sounds good to me, want to make the PR?

**Comment by krainboltgreene** [comment]
Solved by #3
